### ISSUE TITLE
I am tryting to make your kernel working better on U30GT2. 

### ISSUE THREAD

**Issue by ecJon** [aloksinha2001/Linux3188#19]
Hello aloksinha2001.I want to make a better kernel for my U30GT2.I will also try to fix the wifi,if I can~So,can you tell me which .config file is using in your  picuntu-kernel-4.5.img kernel?Thanks a lot.

**Comment by Glavnuck** [comment]
I'm still thinking - whether to install Ubuntu on a 3188 or continue to use
Android.

2013/12/25 ecJon notifications@github.com

> Hello aloksinha2001.I want to make a better kernel for my U30GT2.I will
> also try to fix the wifi,if I can~So,can you tell me which .config file is
> using in your picuntu-kernel-4.5.img kernel.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/aloksinha2001/Linux3188/issues/19
> .

## 

_Mao_

**Comment by itdaniher** [comment]
@ecJon I'm pretty sure https://github.com/aloksinha2001/Linux3188/blob/master/.config was used, although I do not know for sure.

**Comment by aloksinha2001** [comment]
I had posted the .config in forums of freaktab - you should be able to
check there.. if not, do let me know and I will push you the .config... as
I remember it :)

Alok

This message is confidential. It may also be privileged or otherwise protected by work product immunity or other legal rules. If you have received it by mistake, please let us know by e-mail reply and delete it from your system; you may not copy this message or disclose its contents to anyone. Please send us by fax any message containing deadlines as incoming e-mails are not screened for response deadlines. The integrity and security of this message cannot be guaranteed on the Internet.

On Thu, Dec 26, 2013 at 9:12 AM, Ian Daniher notifications@github.comwrote:

> @ecJon https://github.com/ecJon I'm pretty sure
> https://github.com/aloksinha2001/Linux3188/blob/master/.config was used,
> although I do not know for sure.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/aloksinha2001/Linux3188/issues/19#issuecomment-31210342
> .

## 

_Alok Sinha_
Chief Executive Officer,
_Globus Eight_
Suite 600, 2201 Cooperative Way, Herndon, VA, USA 20171
Level 12, Tower 8C, DLF Phase II, Gurgaon, India 122002
Phone: +1-757-447-4642   | +91-9810159444
asinha@g8.net                 | www.g8.net

**Comment by aloksinha2001** [comment]
Were u able to finally make picuntu work on U9GT5 ?

Alok

This message is confidential. It may also be privileged or otherwise protected by work product immunity or other legal rules. If you have received it by mistake, please let us know by e-mail reply and delete it from your system; you may not copy this message or disclose its contents to anyone. Please send us by fax any message containing deadlines as incoming e-mails are not screened for response deadlines. The integrity and security of this message cannot be guaranteed on the Internet.

On Sat, Dec 28, 2013 at 12:21 PM, Alok Sinha asinha@g8.net wrote:

> I had posted the .config in forums of freaktab - you should be able to
> check there.. if not, do let me know and I will push you the .config... as
> I remember it :)
> 
> Alok
> 
> On Thu, Dec 26, 2013 at 9:12 AM, Ian Daniher notifications@github.comwrote:
> 
> > @ecJon https://github.com/ecJon I'm pretty sure
> > https://github.com/aloksinha2001/Linux3188/blob/master/.config was used,
> > although I do not know for sure.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/aloksinha2001/Linux3188/issues/19#issuecomment-31210342
> > .
> 
> ## 
> 
> _Alok Sinha_
> Chief Executive Officer,
> _Globus Eight_
> Suite 600, 2201 Cooperative Way, Herndon, VA, USA 20171
> Level 12, Tower 8C, DLF Phase II, Gurgaon, India 122002
> Phone: +1-757-447-4642   | +91-9810159444
> asinha@g8.net                 | www.g8.net

## 

_Alok Sinha_
Chief Executive Officer,
_Globus Eight_
Suite 600, 2201 Cooperative Way, Herndon, VA, USA 20171
Level 12, Tower 8C, DLF Phase II, Gurgaon, India 122002
Phone: +1-757-447-4642   | +91-9810159444
asinha@g8.net                 | www.g8.net
